require("core.plugin_config.colorscheme")
require("core.plugin_config.harpoon")
require("core.plugin_config.lualine")
require("core.plugin_config.oil")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
